[tox]
envlist =
    py{310,311}-django{42,50,51,52}
    py312-django{42,50,51,52,60}
    py313-django{51,52,60}
    py314-django60
[testenv]
usedevelop = true
commands =
    coverage run {envbindir}/django-admin test --verbosity 2 session_security
deps =
    coverage
    unittest-data-provider
    selenium>=4.0
    django42: Django>=4.2,<4.3
    django50: Django>=5.0,<5.1
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
setenv =
    DJANGO_SETTINGS_MODULE=session_security.tests.project.settings
passenv = CI,DISPLAY,DBDIFF_*,TEST_*,TOX_*,SAUCE_*

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
